import test from 'node:test'
import assert from 'node:assert/strict'
import { mkdtemp, writeFile, rm } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { createHash } from 'node:crypto'
import { assertSourceIdentity, verifyFixtureFiles, assertDistribution } from '../scripts/ci-contract.mjs'
test('CI binds clean source to the exact requested commit', () => {
 const input={actual:'a'.repeat(40),expected:'a'.repeat(40),dirty:''};assert.doesNotThrow(()=>assertSourceIdentity(input))
 for(const changed of [{expected:'main'},{actual:'b'.repeat(40)},{dirty:' M src/index.ts'}]) assert.throws(()=>assertSourceIdentity({...input,...changed}))
})
test('fixture inventory rejects altered or missing files',async()=>{
 const dir=await mkdtemp(join(tmpdir(),'auth-fixture-gate-'))
 try {const data='synthetic vector';await writeFile(join(dir,'vector.json'),data);const manifest={'vector.json':createHash('sha256').update(data).digest('hex')};await verifyFixtureFiles(dir,manifest);await writeFile(join(dir,'vector.json'),'altered vector');await assert.rejects(verifyFixtureFiles(dir,manifest));await rm(join(dir,'vector.json'));await assert.rejects(verifyFixtureFiles(dir,manifest))}finally{await rm(dir,{recursive:true,force:true})}
})
test('generated distribution rejects modified, new and removed outputs',()=>{
 assert.doesNotThrow(()=>assertDistribution(''))
 for(const status of [' M dist/index.js','?? dist/new.js',' D dist/index.d.ts'])assert.throws(()=>assertDistribution(status))
})

test('a committed obsolete dist file cannot pass the real build, CI gate and package boundary', async () => {
 const {cp,mkdir,symlink,readFile} = await import('node:fs/promises')
 const {spawnSync} = await import('node:child_process')
 const {fileURLToPath} = await import('node:url')
 const source=fileURLToPath(new URL('../',import.meta.url)),dir=await mkdtemp(join(tmpdir(),'auth-committed-dist-'))
 const run=(command,args)=>spawnSync(command,args,{cwd:dir,encoding:'utf8',env:{...process.env,npm_config_audit:'false',npm_config_fund:'false'}})
 const ok=(command,args)=>{const r=run(command,args);assert.equal(r.status,0,r.stdout+r.stderr);return r}
 try {
  for(const path of ['src','dist','scripts','package.json','tsconfig.json','tsconfig.build.json','.gitignore'])await cp(join(source,path),join(dir,path),{recursive:true})
  await symlink(join(source,'node_modules'),join(dir,'node_modules'),'dir')
  await mkdir(join(dir,'dist','retired'),{recursive:true})
  await writeFile(join(dir,'dist','retired','obsolete.js'),'export const obsolete = true\n')
  ok('git',['init','--quiet']);ok('git',['add','.']);ok('git',['-c','user.name=Fixture','-c','user.email=fixture@example.invalid','commit','--quiet','-m','Synthetic committed output'])
  // The developer/prepack build must also produce a clean complete tree.
  ok('npm',['run','build'])
  const gate=run(process.execPath,['scripts/check-ci.mjs','dist'])
  assert.notEqual(gate.status,0,'Deleted committed residue must fail the existing CI consistency gate')
  assert.match(gate.stdout+gate.stderr,/dist\/retired\/obsolete\.js/)
  const packed=JSON.parse(ok('npm',['pack','--ignore-scripts','--dry-run','--json']).stdout)[0]
  assert.equal(packed.files.some(file=>file.path.includes('obsolete')),false)
  ok('git',['restore','--','dist'])
  const original=await readFile(join(dir,'dist','index.js'))
  // CI comparison must discover committed residue, without cleaning away its evidence.
  const check=run('npm',['run','build:check'])
  assert.notEqual(check.status,0);assert.match(check.stdout+check.stderr,/obsolete.*retired\/obsolete\.js/)
  assert.deepEqual(await readFile(join(dir,'dist','index.js')),original)
  assert.equal(await readFile(join(dir,'dist','retired','obsolete.js'),'utf8'),'export const obsolete = true\n')
  ok('npm',['run','build']);ok('npm',['run','build:check'])
  for(const mismatch of ['missing','changed']) {
   if(mismatch==='missing')await rm(join(dir,'dist','index.js'))
   else await writeFile(join(dir,'dist','index.js'),'stale generated bytes')
   const rejected=run('npm',['run','build:check'])
   assert.notEqual(rejected.status,0);assert.match(rejected.stdout+rejected.stderr,new RegExp(mismatch+': index\\.js'))
   await writeFile(join(dir,'dist','index.js'),original)
  }
  await writeFile(join(dir,'src','index.ts'),'export const broken = ;')
  assert.notEqual(run('npm',['run','build']).status,0)
  assert.deepEqual(await readFile(join(dir,'dist','index.js')),original,'Compiler failure must retain the previous distribution')

 } finally {await rm(dir,{recursive:true,force:true})}
})
